# Generated by Django 3.2.13 on 2022-05-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_agenda_horarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['-horarios'], 'verbose_name': 'Horario'},
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='horario',
            new_name='horarios',
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('horarios', 'agenda')},
        ),
    ]
