# Generated by Django 3.2.13 on 2022-05-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_alter_agenda_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medico'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='clinica.medico'),
        ),
    ]
