# Generated by Django 3.2.13 on 2022-05-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_auto_20220502_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='clinica.medico'),
        ),
    ]
