# Generated by Django 3.2.13 on 2022-05-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20220502_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['-horarios'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='clinica.horario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horarios',
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia', 'horarios')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='agenda',
        ),
    ]
