# Generated by Django 3.2.13 on 2022-05-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_auto_20220502_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clinica.agenda'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('horarios', 'agenda')},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('dia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda')),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.horario')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_agendamento'],
                'unique_together': {('dia', 'horario', 'medico')},
            },
        ),
    ]
