# Generated by Django 3.2.13 on 2022-05-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_auto_20220502_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clinica.agenda'),
        ),
    ]
