# Generated by Django 3.2.13 on 2022-05-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_alter_horario_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clinica.agenda'),
        ),
    ]
