# Generated by Django 3.2.13 on 2022-05-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_alter_horario_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='clinica.medico'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('dia',)},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='medico',
        ),
    ]
