# Generated by Django 3.2.13 on 2022-05-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0019_auto_20220503_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='clinica.medico'),
        ),
    ]
