# Generated by Django 3.2.13 on 2022-05-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0022_auto_20220503_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-dia'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='clinica.medico'),
        ),
        migrations.AddField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='clinica.agenda'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('horarios',)},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='medico',
        ),
    ]
