# Generated by Django 3.2.13 on 2022-05-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0023_auto_20220503_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='clinica.agenda'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('horarios', 'agenda')},
        ),
    ]
