# Generated by Django 3.2.13 on 2022-05-03 15:34

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0026_alter_horario_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(validators=[clinica.models.Agenda.validate_date]),
        ),
    ]
