# Generated by Django 3.2.13 on 2022-05-03 15:58

import clinica.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0027_alter_agenda_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_id', to='clinica.agenda'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='clinica.horario', validators=[clinica.models.Consulta.validate_date]),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('horario', 'agenda')},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
    ]
