# Generated by Django 3.2.13 on 2022-05-04 17:07

import clinica.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0028_auto_20220503_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_id', to='clinica.agenda', validators=[clinica.models.Consulta.validate_date]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clinica.horario', validators=[clinica.models.Consulta.validate_date_time]),
        ),
    ]
